### ISSUE TITLE
Integrate mofo-style

### ISSUE THREAD

**Issue by toolness** [mozilla/teach.webmaker.org#142] opened 2015-03-05 02:49 UTC
I'm not sure if this is a duplicate or not, but we should integrate with [mofo-style](https://www.npmjs.com/package/mofo-style) and run it as part of our test suite.

**Comment by toolness** [comment] 2015-03-05 02:49
@gesa are you still interested in taking this one on?

**Comment by gesa** [comment] 2015-03-05 02:51
So someone in IRC mentioned that @alicoding might already be on this? Additionally, @gvn & @Pomax are currently applying mofo-style to all the repos. If this isn't on anyone's radar already, I'll **totally** take a stab at it—I just don't want to duplicate work.

Gentlemen, could you all confirm that this isn't already in progress somewhere?

**Comment by Pomax** [comment] 2015-03-05 05:36
This is a currently heartbeat over at https://github.com/MozillaFoundation/plan/issues/351 -- we're on the job.

**Comment by Pomax** [comment] 2015-03-05 05:37
closing this as a duplicate of https://github.com/mozilla/teach.webmaker.org/issues/112 that we're working on this heartbeat

**Comment by toolness** [comment] 2015-03-05 21:21
Er, my understanding was that I was on the hook for integrating mofo-style, and aki expressed interest in it so I delegated it to her. Hmmmm.

**Comment by toolness** [comment] 2015-03-05 21:54
Actually, #142 is quite a doozy and I think it's worth splitting it up into multiple mini-bugs. This is now the mini-bug for integrating mofo-style!

**Comment by Pomax** [comment] 2015-03-06 02:27
Hmm, I don't see your name in the App Matrix for plan/351, can you ask @wex what he wants to have happen here?

**Comment by alicoding** [comment] 2015-03-06 02:27
@Pomax you meant @simonwex :P

**Comment by toolness** [comment] 2015-03-09 17:47
Just talked to him and it looks like I am responsible... @gesa want to bust this up?

**Comment by gesa** [comment] 2015-03-09 17:47
Here we go!

**Comment by simonwex** [comment] 2015-03-09 17:48
@Pomax it's because @alicoding was going to do it, but @toolness is now. Updated spreadsheet.

**Comment by toolness** [comment] 2015-03-09 17:58
Thanks @gesa!

Do you think you could maybe split this up into two separate PRs/issues, the way I did with #137 and #138, where one PR adds *optional* support for style guide checking and the other issue is for fixing all the existing style issues w/ our code? (Or if it's more convenient, multiple issues/PRs could be filed that each fix the style issues in a subset of files.)

**Closed** 2015-03-10 20:36 UTC
