### ISSUE TITLE
create 404 page

### ISSUE THREAD

**Issue by LauraHilliger** [mozilla/teach.webmaker.org#998] opened 2015-06-05 11:27 UTC
We should create a friendly 404 or redirect people to the home page:

http://i.imgur.com/W8kpRHN.png

**Comment by toolness** [comment] 2015-06-05 11:55
Aww yeah! jess actually started work on this in #406, which this is basically a dupe of, so I'm closin' it.

**Closed** 2015-06-05 11:57 UTC
Labels: design, engineering, grooming, help wanted
