### ISSUE TITLE
Remove hyperlink if Club url field left blank

### ISSUE THREAD

**Issue by ldecoursy** [mozilla/teach.webmaker.org#534] opened 2015-04-01 19:58 UTC
I added a group to the map (Firefox with Android), however didn't enter my club's URL - which may be the case for others that don't have a web presence. 

On the list of clubs on http://teach.mofostaging.net/mozilla-web-clubs/, when I click the link for my club "PS 295 Web Club" it just takes me to the main Clubs page. 

Two places to remove the hyperlink:
 - [x] The map callout view should not show a link at all if the url field is left blank 
 - [ ] The list view should not hyperlink the name of the Club if the url field is left blank

**Comment by hannahkane** [comment] 2015-04-01 23:10
Agree Clubs with no url should not be hyperlinked at all.

**Comment by iamjessklein** [comment] 2015-04-02 13:27
My thought was that if a club has no url, it could link to the issuers webmaker profile. Otherwise an onl looker will have no way of getting more information, right?

**Comment by hannahkane** [comment] 2015-04-02 16:27
Ah, right. I remember talking about that. What do you think about always linking to the creator's webmaker profile, and also linking to a url if provided, but not linking if not provided?

@iamjessklein - if that makes sense to you, I'll file a ticket for that.

**Comment by iamjessklein** [comment] 2015-04-02 16:38
:+1:

**Comment by hannahkane** [comment] 2015-04-06 18:16
Added #591 to address adding and linking the username. But this ticket is still valid.

**Comment by hannahkane** [comment] 2015-04-10 19:59
@ScottDowne - if you're no longer on Teach duty, want to un-assign?

**Comment by hannahkane** [comment] 2015-04-17 16:16
@ScottDowne - were you able to start on this one?

**Comment by mmmavis** [comment] 2015-04-17 22:30
@ScottDowne I feel like doing some small tasks on Friday afternoon so I decided to steal your ticket.  Review my PR plz? https://github.com/mozilla/teach.webmaker.org/pull/719 :grin: 

Also I checked on staging for the issue @ldecoursy mentioned (re: The map callout view should not show a link at all if the url field is left blank)
![screen shot 2015-04-17 at 3 22 20 pm](https://cloud.githubusercontent.com/assets/2896608/7212030/78181c8a-e516-11e4-8f38-e539d0b2039e.png)
I can't reproduce the issue so I guess it has been fixed already?

**Comment by hannahkane** [comment] 2015-04-17 22:42
I believe the other issue was resolved in #591.

**Comment by mmmavis** [comment] 2015-04-18 00:10
@ScottDowne , this ticket can be closed now, correct?

**Comment by ScottDowne** [comment] 2015-04-18 00:20
Maybe, something doesn't add up and I'm writing a comment to explain it.

I was figuring out if we can close or not.

**Comment by ScottDowne** [comment] 2015-04-18 00:23
Something doesn't add up still.

"The map callout view should not show a link at all if the url field is left blank "

Looking at the code, from what I can tell, there was never a moment where you could create a club with no website and have it display a link in the map view.

If you look at this commit:

https://github.com/mozilla/teach.webmaker.org/commit/0b6ea97667c47e3359226a5355e9dcfa9a0be799

That landed before this issue was opened, and ensured a website didn't display if it wasn't added to the club, also changed the website url from required to optional.

 Thoughts?

**Comment by ScottDowne** [comment] 2015-04-18 00:24
Meh, closing, if it's still an issue we should file a new issue to reduce confusion.

**Closed by ScottDowne** 2015-04-18 00:24 UTC
Labels: bug, engineering, platform, v1
