### ISSUE TITLE
Split this repo into two

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.webmaker.org#807] opened 2015-04-23 18:28 UTC
<img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migration.png">

1) Should include all tickets tagged with "platform" and should be called teach.mozilla.org

2) Should include all tickets NOT tagged with "platform" and should be called mozilla-learning

**Comment by simonwex** [comment] 2015-04-23 21:39
Hey @toolness, I chucked your name down here instead of mine. I'm pretty bogged down these days and I don't want to delay the improvements to teach team's lives.

**Comment by toolness** [comment] 2015-04-24 23:03
Ok, I am attempting to build a solution at https://github.com/toolness/learning-issue-migrator.

**Comment by toolness** [comment] 2015-04-27 12:52
Ok, it looks like the `platform` label isn't actually exhaustive here... This is the current criteria for determining whether an issue goes into the **teach.mozilla.org** repo:

* the issue has the [`platform`](https://github.com/mozilla/teach.webmaker.org/issues?q=label%3Aplatform) label, **or**
* the issue has the [`bug`](https://github.com/mozilla/teach.webmaker.org/issues?q=label%3Abug) label, **or**
* the issue has the [`engineering`](https://github.com/mozilla/teach.webmaker.org/issues?q=label%3Aengineering) label, **or**
* the issue is actually a [pull request](https://github.com/mozilla/teach.webmaker.org/pulls?q=is%3Apr) (all PRs are issues in GitHub).

If *any* of the above criteria are met, then the issue is essentially considered a teach.mozilla.org issue. Does that sound reasonable?

Even with this criteria, I'm finding issues that are platform issues but meet none of the above criteria; I'm giving them the `platform` label now so that they don't accidentally end up in the wrong repo. After that, I should probably go through the platform issues to make sure none of them are actually mozilla-learning issues.

**Comment by hannahkane** [comment] 2015-04-30 16:59
OK, we are good to go with /mozilla/learning-networks

@toolness - please do send the test ones over so @ldecoursy, @thornet and I can take a look.

**Comment by toolness** [comment] 2015-04-30 18:47
Ok! I just made the repository and migrated #11 and #12 (the oldest non-platform tickets) over to it. Can you check those to make sure everything looks ok?

To clarify, there should be a link at the bottom of the "old" issue that looks like this:

![2015-04-30_14-38-37](https://cloud.githubusercontent.com/assets/124687/7419961/a936e604-ef46-11e4-9ce0-a8e9f3152d6a.png)

and the "new" issue links back to the old one, has the same labels and milestone and assignee and closed/open state, and its description contains the quoted content of the old issue's description and all its comments:

![2015-04-30_14-40-17](https://cloud.githubusercontent.com/assets/124687/7420006/fc1671fa-ef46-11e4-80a1-15d484ec48b2.png)

Note also that ticket numbers have been preserved. For instance, the description in the old ticket may look like this:

![screen shot 2015-04-30 at 2 44 43 pm](https://cloud.githubusercontent.com/assets/124687/7420088/9441e40a-ef47-11e4-9046-faff175c289e.png)

while in the new ticket it gets re-written as this:

![screen shot 2015-04-30 at 2 44 59 pm](https://cloud.githubusercontent.com/assets/124687/7420090/9edd7794-ef47-11e4-9f60-83c1f4140274.png)

Additionally, if the old issue wasn't already closed, it will be after migration, since the new issue supersedes it.

Once you give me the OK, I'll go ahead and migrate the rest of the issues!

**Comment by hannahkane** [comment] 2015-04-30 18:49
awesome work, @toolness! +1 from me.

**Comment by toolness** [comment] 2015-04-30 18:51
Hooray, thanks!

Should I go ahead and migrate the rest of the tickets or should we wait for lainie and michelle to take a look?

**Comment by hannahkane** [comment] 2015-04-30 18:55
Let's wait for @ldecoursy to weigh in, since @thornet may not be able to until tomorrow.

**Comment by ldecoursy** [comment] 2015-04-30 19:16
It looks good to me. Can you let us know what happens when a ticket is linked from another repo (/plan for instance) or from an etherpad? Guess I'm wondering if those links will all be dead or if they'll redirect, or if there's a note in the closed ticket on this repo that it was migrated to another repo.

**Comment by toolness** [comment] 2015-04-30 20:09
They won't be dead links--they'll just link to the "old" issue, which will have the "This Issue Has Migrated" comment/image at the bottom.

If you want, we could also prepend the name of the old ticket with the word "[MIGRATED]" so it's more obvious.

**Comment by toolness** [comment] 2015-05-01 00:26
Ok, only 47 tickets left to migrate!

Unfortunately, my script is triggering GitHub's [Abuse Rate Limits](https://developer.github.com/v3/#abuse-rate-limits) so it's going a bit slower than I hoped.

I also really wish there was a way to tell the GitHub API not to send transactional emails for the changes I'm making through it, because this is spamming a lot of people. :(

**Comment by toolness** [comment] 2015-05-01 01:18
Woot it is done!!!!!! I'm closing this issue now.

**Closed by toolness** 2015-05-01 01:18 UTC
Labels: In Progress, platform

**Comment by jgmac1106** [comment] 2015-05-01 01:43
<img src="http://i.imgur.com/6Loa1WM.png?1">
