### ISSUE TITLE
MOBILE: In navigation the Clubs Toolkit is hidden

### ISSUE THREAD

**Issue by iamjessklein** [mozilla/teach.webmaker.org#510] opened 2015-04-01 15:04 UTC
When Mozilla web clubs is selected, the child section Clubs Toolkit is dissected and does not fully show.

**Comment by sabrinang** [comment] 2015-04-01 16:58
![screenshot_navigation_clubs-toolkit](https://cloud.githubusercontent.com/assets/2492510/6946495/83415b62-d855-11e4-898a-9286ceca57fe.png)

**Comment by jamieleung** [comment] 2015-04-01 18:33
It appears adding `height: 100%` to `.sidebar` could fix this issue, shall I go ahead and apply this fix?
![screen shot 2015-04-01 at 19 31 36](https://cloud.githubusercontent.com/assets/285441/6948458/db5c2a3e-d8a5-11e4-866f-2c1d8e33073b.png)

**Comment by iamjessklein** [comment] 2015-04-01 19:34
Yeah that would be rad @jamieleung - we will check out the PR. :+1:  Thanks

**Comment by toolness** [comment] 2015-04-06 11:30
Er, isn't this a duplicate of #423?

**Comment by iamjessklein** [comment] 2015-04-06 13:03
indeed it is @toolness @ScottDowne

**Comment by toolness** [comment] 2015-04-06 13:43
Ok, I guess I will close it as a DUPE then!

**Closed by toolness** 2015-04-06 13:43 UTC
Labels: design, engineering, platform, QA, v1
