### ISSUE TITLE
redirect teach.webmaker.org to teach.mozilla.org

### ISSUE THREAD

**Issue by LauraHilliger** [mozilla/teach.webmaker.org#961] opened 2015-06-01 08:21 UTC
just got sent a journal article that points readers to teach.webmaker.org, which doesn't exist. Would be good to redirect.

**Comment by toolness** [comment] 2015-06-01 10:20
Hey this is a dupe of #778!! I'll reopen that.

**Closed by toolness** 2015-06-01 10:20 UTC
