### ISSUE TITLE
Map the communications model for RCs

### ISSUE THREAD

**Issue by Saallen** [mozilla/teach.webmaker.org#19] opened 2015-02-12 22:34 UTC
Develop the call structure for RC's with organisers and other RCs.

## RACI

* Phase: 
* Owner: 
* Decision Maker: 
* Design Lead: 
* Development Lead: 
* Quality Verifier: 

## Deliverables

 - [ ] TBD

**Comment by thornet** [comment] 2015-03-16 15:24
Duplicate of #20, closing

**Closed by thornet** 2015-03-16 15:24 UTC
Labels: leadership

**Comment by toolness** [comment] 2015-04-30 22:52
<a href="https://github.com/mozilla/learning-networks/issues/9"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/learning-networks/issues/9.
Please don't comment on it here.
