### ISSUE TITLE
404 for poster image on /events/resources/

### ISSUE THREAD

**Issue by alicoding** [mozilla/teach.webmaker.org#845] opened 2015-04-30 14:23 UTC
https://teach.mozilla.org/events/resources/

![](https://dl.dropboxusercontent.com/spa/n5v3bx9nnjkdpzf/j8mcs3b4.png)

**Comment by hannahkane** [comment] 2015-04-30 16:30
I can't reproduce this

**Comment by toolness** [comment] 2015-04-30 20:58
Hmmmmm, I can't either...

**Comment by alicoding** [comment] 2015-05-01 13:43
Weird... I still can't get the image to display here...
https://teach.mozilla.org/img/event-resources-page/resource-thumbnails-07@2x.png

**Comment by toolness** [comment] 2015-05-01 14:47
Ahhh you're right! I'm looking at it in on my retina laptop now and it's indeed not working.

This has actually been fixed in #840 and will be included in our next push to production (#847). You can see the analogous link does exist on staging: https://teach.mofostaging.net/img/event-resources-page/resource-thumbnails-07@2x.png.

So, closing this bug as it'll be fixed as soon as #847 is resolved!

**Closed by toolness** 2015-05-01 14:47 UTC
Labels: platform
